### PR TITLE
Fixed a miscalculation in the dribbler bar speed

### PR DESCRIPTION
**Pull request by emielsteerneman**

### CODE REVIEW

**Comment by emielsteerneman** [comment]
Tested it by hand, the fix is working

**Review by supertom01 — APPROVED** [review]
Looks gucci

**Comment by skaeringur97** [comment]
Plz test the dribbler "ball sensor" with AI before merging. The dribbler "ball sensor" works differently on the python scripts and AI. And, until we get an actual ball sensor, the dribbler "ball sensor" is more important than having accurate dribble measurements.

**Comment by supertom01** [comment]
@JAndringa or @silashoevers could one of the AI team people take a look at how the AI utilizes the 'ball sensor' functionality of the dribbler? Especially on how the bar speed is used in the detection of the ball

**Comment by skaeringur97** [comment]
> @JAndringa or @silashoevers could one of the AI team people take a look at how the AI utilizes the 'ball sensor' functionality of the dribbler? Especially on how the bar speed is used in the detection of the ball

I made this functionality on the control side, Alex made the functionality on the AI side. Contact us on discord if you have questions

**Pull request merged**
