### PR TITLE
Fix compatibility with CubeMX 6.6.1

### PR DESCRIPTION
**Pull request by supertom01**

### CODE REVIEW

**Review by emielsteerneman — APPROVED** [review]
Lgtm. @casdoorn?

**Review by casdoorn — APPROVED** [review]
Looks good. I assume you checked the changes within NVIC? Some flags went from true to false.

**Comment by emielsteerneman** [comment]
Atm we only checked if it compiled and it did. Might indeed be a good plan to upload it to a robot and test it. @supertom01 We could do that tomorrow

**Comment by supertom01** [comment]
I did actually upload it to robot 13, however it's wheels were already not turning before the upload. So a proper test could indeed be done tomorrow

**Comment by emielsteerneman** [comment]
tried and tested

**Pull request merged**
